In [6]:
import pandas as pd

In [7]:
df = pd.read_csv("https://github.com/singhrau0/Big-Data-Preprocessing/raw/refs/heads/main/fifa21_raw_data.csv")

C:\Users\mabhi\AppData\Local\Temp\ipykernel_9740\2208447333.py:1: DtypeWarning: Columns (76) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("https://github.com/singhrau0/Big-Data-Preprocessing/raw/refs/heads/main/fifa21_raw_data.csv")

In [8]:
pd.set_option("display.max_columns",None)

In [9]:
df

,photoUrl,LongName,playerUrl,Nationality,Positions,Name,Age,↓OVA,POT,Team & Contract,ID,Height,Weight,foot,BOV,BP,Growth,Joined,Loan Date End,Value,Wage,Release Clause,Attacking,Crossing,Finishing,Heading Accuracy,Short Passing,Volleys,Skill,Dribbling,Curve,FK Accuracy,Long Passing,Ball Control,Movement,Acceleration,Sprint Speed,Agility,Reactions,Balance,Power,Shot Power,Jumping,Stamina,Strength,Long Shots,Mentality,Aggression,Interceptions,Positioning,Vision,Penalties,Composure,Defending,Marking,Standing Tackle,Sliding Tackle,Goalkeeping,GK Diving,GK Handling,GK Kicking,GK Positioning,GK Reflexes,Total Stats,Base Stats,W/F,SM,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits
0,https://cdn.sofifa.com/players/158/023/21_60.png,Lionel Messi,http://sofifa.com/player/158023/lionel-messi/2...,Argentina,RW ST CF,L. Messi,33,93,93,\n\n\n\nFC Barcelona\n2004 ~ 2021\n\n,158023,"5'7""",159lbs,Left,93,RW,0,"Jul 1, 2004",NaN,€67.5M,€560K,€138.4M,429,85,95,70,91,88,470,96,93,94,91,96,451,91,80,91,94,95,389,86,68,72,69,94,347,44,40,93,95,75,96,91,32,35,24,54,6,11,15,14,8,2231,466,4 ★,4★,Medium,Low,5 ★,85,92,91,95,38,65,\n372
1,https://cdn.sofifa.com/players/020/801/21_60.png,C. Ronaldo dos Santos Aveiro,http://sofifa.com/player/20801/c-ronaldo-dos-s...,Portugal,ST LW,Cristiano Ronaldo,35,92,92,\n\n\n\nJuventus\n2018 ~ 2022\n\n,20801,"6'2""",183lbs,Right,92,ST,0,"Jul 10, 2018",NaN,€46M,€220K,€75.9M,437,84,95,90,82,86,414,88,81,76,77,92,431,87,91,87,95,71,444,94,95,84,78,93,353,63,29,95,82,84,95,84,28,32,24,58,7,11,15,14,11,2221,464,4 ★,5★,High,Low,5 ★,89,93,81,89,35,77,\n344
2,https://cdn.sofifa.com/players/200/389/21_60.png,Jan Oblak,http://sofifa.com/player/200389/jan-oblak/210005/,Slovenia,GK,J. Oblak,27,91,93,\n\n\n\nAtlético Madrid\n2014 ~ 2023\n\n,200389,"6'2""",192lbs,Right,91,GK,2,"Jul 16, 2014",NaN,€75M,€125K,€159.4M,95,13,11,15,43,13,109,12,13,14,40,30,307,43,60,67,88,49,268,59,78,41,78,12,140,34,19,11,65,11,68,57,27,12,18,437,87,92,78,90,90,1413,489,3 ★,1★,Medium,Medium,3 ★,87,92,78,90,52,90,\n86
3,https://cdn.sofifa.com/players/192/985/21_60.png,Kevin De Bruyne,http://sofifa.com/player/192985/kevin-de-bruyn...,Belgium,CAM CM,K. De Bruyne,29,91,91,\n\n\n\nManchester City\n2015 ~ 2023\n\n,192985,"5'11""",154lbs,Right,91,CAM,0,"Aug 30, 2015",NaN,€87M,€370K,€161M,407,94,82,55,94,82,441,88,85,83,93,92,398,77,76,78,91,76,408,91,63,89,74,91,408,76,66,88,94,84,91,186,68,65,53,56,15,13,5,10,13,2304,485,5 ★,4★,High,High,4 ★,76,86,93,88,64,78,\n163
4,https://cdn.sofifa.com/players/190/871/21_60.png,Neymar da Silva Santos Jr.,http://sofifa.com/player/190871/neymar-da-silv...,Brazil,LW CAM,Neymar Jr,28,91,91,\n\n\n\nParis Saint-Germain\n2017 ~ 2022\n\n,190871,"5'9""",150lbs,Right,91,LW,0,"Aug 3, 2017",NaN,€90M,€270K,€166.5M,408,85,87,62,87,87,448,95,88,89,81,95,453,94,89,96,91,83,357,80,62,81,50,84,356,51,36,87,90,92,93,94,35,30,29,59,9,9,15,15,11,2175,451,5 ★,5★,High,Medium,5 ★,91,85,86,94,36,59,\n273
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18974,https://cdn.sofifa.com/players/257/710/21_60.png,Mengxuan Zhang,http://sofifa.com/player/257710/mengxuan-zhang...,China PR,CB,Zhang Mengxuan,21,47,52,\n\n\n\nChongqing Dangdai Lifan FC SWM Team\n2...,257710,"5'10""",154lbs,Right,49,CB,5,"Aug 1, 2020",NaN,€35K,€1K,€57K,141,23,16,45,31,26,111,19,21,22,25,24,279,60,56,45,48,70,223,35,65,55,45,23,179,44,50,25,25,35,40,148,45,56,47,53,12,13,8,14,6,1134,232,2 ★,2★,Low,Low,1 ★,58,23,26,27,50,48,2
18975,https://cdn.sofifa.com/players/258/736/21_60.png,Vani Da Silva,http://sofifa.com/player/258736/vani-da-silva/...,England,ST,V. Da Silva,17,47,67,\n\n\n\nOldham Athletic\n2020 ~ 2021\n\n,258736,"5'7""",128lbs,Right,51,CAM,20,"Aug 1, 2020",NaN,€60K,€500,€165K,202,27,47,36,45,47,208,53,43,31,37,44,339,69,70,67,53,80,231,50,50,55,35,41,186,33,11,43,49,50,45,42,18,11,13,48,11,13,9,9,6,1256,265,2 ★,2★,Medium,Medium,1 ★,70,46,40,53,16,40,3
18976,https://cdn.sofifa.com/players/247/223/21_60.png,Ao Xia,http://sofifa.com/player/247223/ao-xia/210005/,China PR,CB,Xia Ao,21,47,55,\n\n\n\nWuhan Zall\n2018 ~ 2022\n\n,247223,"5'10""",146lbs,Right,49,CB,8,"Jul 13, 2018",NaN,€40K,€1K,€70K,145,23,26,43,26,27,142,27,23,21,29,42,294,68,60,69,46,51,221,36,57,54,50,24,192,48,50,28,28,38,44,147,45,52,50,45,7,8,5,14,11,1186,255,2 ★,2★,Medium,Medium,1 ★,64,28,26,38,48,51,3
18977,https://cdn.sofifa.com/players/258/760/21_60.png,Ben Hough,http://sofifa.com/player/258760/ben-hough/210005/,England,CM,B. Hough,17,47,67,\n\n\n\nOldham Athletic\n2020 ~ 2021\n\n,258760,"5'9""",143lbs,Right,51,CAM,20,"Aug 1, 2020",NaN,€60K,€500,€165K,211,38,42,40,56,35,219,46,40,35,50,48,305,63,64,61,51,66,226,48,58,43,47,30,193,40,23,47,47,36,38,116,32,44,40,45,12,10,9,6,8,1315,281,2 ★,2★,Medium,Medium,1 ★,64,40,48,49,35,45,5
18978,https://cdn.sofifa.com/players/255/958/21_60.png,Mateo Flores,http://sofifa.com/player/255958/mateo-flores/2...,Bolivia,CDM,M. Flores,19,47,63,\n\n\n\nClub Bolívar\n2020 ~ 2024\n\n,255958,"5'9""",150lbs,Right,48,CDM,16,"Jan 1, 2020",NaN,€60K,€500,€167K,191,32,27,48,52,32,198,45,31,32,47,43,298,55,59,59,50,75,223,41,55,47,47,33,206,57,45,30,39,35,36,129,43,41,45,56,10,8,15,9,14,1301,273,3 ★,2★,Medium,Medium,1 ★,57,32,43,48,44,49,2

In [10]:
# drop unnecessary columns 
df.drop(['photoUrl', 'playerUrl'],axis = 1,inplace=True)

In [11]:
df.drop('Name', axis= 1, inplace=True)

In [12]:
df

,LongName,Nationality,Positions,Age,↓OVA,POT,Team & Contract,ID,Height,Weight,foot,BOV,BP,Growth,Joined,Loan Date End,Value,Wage,Release Clause,Attacking,Crossing,Finishing,Heading Accuracy,Short Passing,Volleys,Skill,Dribbling,Curve,FK Accuracy,Long Passing,Ball Control,Movement,Acceleration,Sprint Speed,Agility,Reactions,Balance,Power,Shot Power,Jumping,Stamina,Strength,Long Shots,Mentality,Aggression,Interceptions,Positioning,Vision,Penalties,Composure,Defending,Marking,Standing Tackle,Sliding Tackle,Goalkeeping,GK Diving,GK Handling,GK Kicking,GK Positioning,GK Reflexes,Total Stats,Base Stats,W/F,SM,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits
0,Lionel Messi,Argentina,RW ST CF,33,93,93,\n\n\n\nFC Barcelona\n2004 ~ 2021\n\n,158023,"5'7""",159lbs,Left,93,RW,0,"Jul 1, 2004",NaN,€67.5M,€560K,€138.4M,429,85,95,70,91,88,470,96,93,94,91,96,451,91,80,91,94,95,389,86,68,72,69,94,347,44,40,93,95,75,96,91,32,35,24,54,6,11,15,14,8,2231,466,4 ★,4★,Medium,Low,5 ★,85,92,91,95,38,65,\n372
1,C. Ronaldo dos Santos Aveiro,Portugal,ST LW,35,92,92,\n\n\n\nJuventus\n2018 ~ 2022\n\n,20801,"6'2""",183lbs,Right,92,ST,0,"Jul 10, 2018",NaN,€46M,€220K,€75.9M,437,84,95,90,82,86,414,88,81,76,77,92,431,87,91,87,95,71,444,94,95,84,78,93,353,63,29,95,82,84,95,84,28,32,24,58,7,11,15,14,11,2221,464,4 ★,5★,High,Low,5 ★,89,93,81,89,35,77,\n344
2,Jan Oblak,Slovenia,GK,27,91,93,\n\n\n\nAtlético Madrid\n2014 ~ 2023\n\n,200389,"6'2""",192lbs,Right,91,GK,2,"Jul 16, 2014",NaN,€75M,€125K,€159.4M,95,13,11,15,43,13,109,12,13,14,40,30,307,43,60,67,88,49,268,59,78,41,78,12,140,34,19,11,65,11,68,57,27,12,18,437,87,92,78,90,90,1413,489,3 ★,1★,Medium,Medium,3 ★,87,92,78,90,52,90,\n86
3,Kevin De Bruyne,Belgium,CAM CM,29,91,91,\n\n\n\nManchester City\n2015 ~ 2023\n\n,192985,"5'11""",154lbs,Right,91,CAM,0,"Aug 30, 2015",NaN,€87M,€370K,€161M,407,94,82,55,94,82,441,88,85,83,93,92,398,77,76,78,91,76,408,91,63,89,74,91,408,76,66,88,94,84,91,186,68,65,53,56,15,13,5,10,13,2304,485,5 ★,4★,High,High,4 ★,76,86,93,88,64,78,\n163
4,Neymar da Silva Santos Jr.,Brazil,LW CAM,28,91,91,\n\n\n\nParis Saint-Germain\n2017 ~ 2022\n\n,190871,"5'9""",150lbs,Right,91,LW,0,"Aug 3, 2017",NaN,€90M,€270K,€166.5M,408,85,87,62,87,87,448,95,88,89,81,95,453,94,89,96,91,83,357,80,62,81,50,84,356,51,36,87,90,92,93,94,35,30,29,59,9,9,15,15,11,2175,451,5 ★,5★,High,Medium,5 ★,91,85,86,94,36,59,\n273
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18974,Mengxuan Zhang,China PR,CB,21,47,52,\n\n\n\nChongqing Dangdai Lifan FC SWM Team\n2...,257710,"5'10""",154lbs,Right,49,CB,5,"Aug 1, 2020",NaN,€35K,€1K,€57K,141,23,16,45,31,26,111,19,21,22,25,24,279,60,56,45,48,70,223,35,65,55,45,23,179,44,50,25,25,35,40,148,45,56,47,53,12,13,8,14,6,1134,232,2 ★,2★,Low,Low,1 ★,58,23,26,27,50,48,2
18975,Vani Da Silva,England,ST,17,47,67,\n\n\n\nOldham Athletic\n2020 ~ 2021\n\n,258736,"5'7""",128lbs,Right,51,CAM,20,"Aug 1, 2020",NaN,€60K,€500,€165K,202,27,47,36,45,47,208,53,43,31,37,44,339,69,70,67,53,80,231,50,50,55,35,41,186,33,11,43,49,50,45,42,18,11,13,48,11,13,9,9,6,1256,265,2 ★,2★,Medium,Medium,1 ★,70,46,40,53,16,40,3
18976,Ao Xia,China PR,CB,21,47,55,\n\n\n\nWuhan Zall\n2018 ~ 2022\n\n,247223,"5'10""",146lbs,Right,49,CB,8,"Jul 13, 2018",NaN,€40K,€1K,€70K,145,23,26,43,26,27,142,27,23,21,29,42,294,68,60,69,46,51,221,36,57,54,50,24,192,48,50,28,28,38,44,147,45,52,50,45,7,8,5,14,11,1186,255,2 ★,2★,Medium,Medium,1 ★,64,28,26,38,48,51,3
18977,Ben Hough,England,CM,17,47,67,\n\n\n\nOldham Athletic\n2020 ~ 2021\n\n,258760,"5'9""",143lbs,Right,51,CAM,20,"Aug 1, 2020",NaN,€60K,€500,€165K,211,38,42,40,56,35,219,46,40,35,50,48,305,63,64,61,51,66,226,48,58,43,47,30,193,40,23,47,47,36,38,116,32,44,40,45,12,10,9,6,8,1315,281,2 ★,2★,Medium,Medium,1 ★,64,40,48,49,35,45,5
18978,Mateo Flores,Bolivia,CDM,19,47,63,\n\n\n\nClub Bolívar\n2020 ~ 2024\n\n,255958,"5'9""",150lbs,Right,48,CDM,16,"Jan 1, 2020",NaN,€60K,€500,€167K,191,32,27,48,52,32,198,45,31,32,47,43,298,55,59,59,50,75,223,41,55,47,47,33,206,57,45,30,39,35,36,129,43,41,45,56,10,8,15,9,14,1301,273,3 ★,2★,Medium,Medium,1 ★,57,32,43,48,44,49,2

In [13]:
df['LongName'].unique()

array(['Lionel Messi', 'C. Ronaldo dos Santos Aveiro', 'Jan Oblak', ...,
       'Ao Xia', 'Ben Hough', 'Mateo Flores'],
      shape=(18851,), dtype=object)

In [14]:
df['LongName'].count()

np.int64(18979)

In [15]:
df['LongName'].value_counts()

LongName
Nicolás González       3
Diego Rodríguez        3
Liam Kelly             3
Danny Rose             3
Adama Traoré           3
                      ..
Manuel Neuer           1
Karim Benzema          1
Sergio Ramos García    1
Sergio Agüero          1
Kevin De Bruyne        1
Name: count, Length: 18851, dtype: int64

In [16]:
s = df.isnull().sum()

In [17]:
# find which column is null
s[s>0]

Loan Date End    17966
dtype: int64

In [18]:
# drop Loan date end column
df.drop(['Loan Date End'], axis=1, inplace=True)

In [19]:
df

,LongName,Nationality,Positions,Age,↓OVA,POT,Team & Contract,ID,Height,Weight,foot,BOV,BP,Growth,Joined,Value,Wage,Release Clause,Attacking,Crossing,Finishing,Heading Accuracy,Short Passing,Volleys,Skill,Dribbling,Curve,FK Accuracy,Long Passing,Ball Control,Movement,Acceleration,Sprint Speed,Agility,Reactions,Balance,Power,Shot Power,Jumping,Stamina,Strength,Long Shots,Mentality,Aggression,Interceptions,Positioning,Vision,Penalties,Composure,Defending,Marking,Standing Tackle,Sliding Tackle,Goalkeeping,GK Diving,GK Handling,GK Kicking,GK Positioning,GK Reflexes,Total Stats,Base Stats,W/F,SM,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits
0,Lionel Messi,Argentina,RW ST CF,33,93,93,\n\n\n\nFC Barcelona\n2004 ~ 2021\n\n,158023,"5'7""",159lbs,Left,93,RW,0,"Jul 1, 2004",€67.5M,€560K,€138.4M,429,85,95,70,91,88,470,96,93,94,91,96,451,91,80,91,94,95,389,86,68,72,69,94,347,44,40,93,95,75,96,91,32,35,24,54,6,11,15,14,8,2231,466,4 ★,4★,Medium,Low,5 ★,85,92,91,95,38,65,\n372
1,C. Ronaldo dos Santos Aveiro,Portugal,ST LW,35,92,92,\n\n\n\nJuventus\n2018 ~ 2022\n\n,20801,"6'2""",183lbs,Right,92,ST,0,"Jul 10, 2018",€46M,€220K,€75.9M,437,84,95,90,82,86,414,88,81,76,77,92,431,87,91,87,95,71,444,94,95,84,78,93,353,63,29,95,82,84,95,84,28,32,24,58,7,11,15,14,11,2221,464,4 ★,5★,High,Low,5 ★,89,93,81,89,35,77,\n344
2,Jan Oblak,Slovenia,GK,27,91,93,\n\n\n\nAtlético Madrid\n2014 ~ 2023\n\n,200389,"6'2""",192lbs,Right,91,GK,2,"Jul 16, 2014",€75M,€125K,€159.4M,95,13,11,15,43,13,109,12,13,14,40,30,307,43,60,67,88,49,268,59,78,41,78,12,140,34,19,11,65,11,68,57,27,12,18,437,87,92,78,90,90,1413,489,3 ★,1★,Medium,Medium,3 ★,87,92,78,90,52,90,\n86
3,Kevin De Bruyne,Belgium,CAM CM,29,91,91,\n\n\n\nManchester City\n2015 ~ 2023\n\n,192985,"5'11""",154lbs,Right,91,CAM,0,"Aug 30, 2015",€87M,€370K,€161M,407,94,82,55,94,82,441,88,85,83,93,92,398,77,76,78,91,76,408,91,63,89,74,91,408,76,66,88,94,84,91,186,68,65,53,56,15,13,5,10,13,2304,485,5 ★,4★,High,High,4 ★,76,86,93,88,64,78,\n163
4,Neymar da Silva Santos Jr.,Brazil,LW CAM,28,91,91,\n\n\n\nParis Saint-Germain\n2017 ~ 2022\n\n,190871,"5'9""",150lbs,Right,91,LW,0,"Aug 3, 2017",€90M,€270K,€166.5M,408,85,87,62,87,87,448,95,88,89,81,95,453,94,89,96,91,83,357,80,62,81,50,84,356,51,36,87,90,92,93,94,35,30,29,59,9,9,15,15,11,2175,451,5 ★,5★,High,Medium,5 ★,91,85,86,94,36,59,\n273
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18974,Mengxuan Zhang,China PR,CB,21,47,52,\n\n\n\nChongqing Dangdai Lifan FC SWM Team\n2...,257710,"5'10""",154lbs,Right,49,CB,5,"Aug 1, 2020",€35K,€1K,€57K,141,23,16,45,31,26,111,19,21,22,25,24,279,60,56,45,48,70,223,35,65,55,45,23,179,44,50,25,25,35,40,148,45,56,47,53,12,13,8,14,6,1134,232,2 ★,2★,Low,Low,1 ★,58,23,26,27,50,48,2
18975,Vani Da Silva,England,ST,17,47,67,\n\n\n\nOldham Athletic\n2020 ~ 2021\n\n,258736,"5'7""",128lbs,Right,51,CAM,20,"Aug 1, 2020",€60K,€500,€165K,202,27,47,36,45,47,208,53,43,31,37,44,339,69,70,67,53,80,231,50,50,55,35,41,186,33,11,43,49,50,45,42,18,11,13,48,11,13,9,9,6,1256,265,2 ★,2★,Medium,Medium,1 ★,70,46,40,53,16,40,3
18976,Ao Xia,China PR,CB,21,47,55,\n\n\n\nWuhan Zall\n2018 ~ 2022\n\n,247223,"5'10""",146lbs,Right,49,CB,8,"Jul 13, 2018",€40K,€1K,€70K,145,23,26,43,26,27,142,27,23,21,29,42,294,68,60,69,46,51,221,36,57,54,50,24,192,48,50,28,28,38,44,147,45,52,50,45,7,8,5,14,11,1186,255,2 ★,2★,Medium,Medium,1 ★,64,28,26,38,48,51,3
18977,Ben Hough,England,CM,17,47,67,\n\n\n\nOldham Athletic\n2020 ~ 2021\n\n,258760,"5'9""",143lbs,Right,51,CAM,20,"Aug 1, 2020",€60K,€500,€165K,211,38,42,40,56,35,219,46,40,35,50,48,305,63,64,61,51,66,226,48,58,43,47,30,193,40,23,47,47,36,38,116,32,44,40,45,12,10,9,6,8,1315,281,2 ★,2★,Medium,Medium,1 ★,64,40,48,49,35,45,5
18978,Mateo Flores,Bolivia,CDM,19,47,63,\n\n\n\nClub Bolívar\n2020 ~ 2024\n\n,255958,"5'9""",150lbs,Right,48,CDM,16,"Jan 1, 2020",€60K,€500,€167K,191,32,27,48,52,32,198,45,31,32,47,43,298,55,59,59,50,75,223,41,55,47,47,33,206,57,45,30,39,35,36,129,43,41,45,56,10,8,15,9,14,1301,273,3 ★,2★,Medium,Medium,1 ★,57,32,43,48,44,49,2

In [20]:
df['POT'].dtypes

dtype('int64')

In [21]:
df['Team & Contract'] = df['Team & Contract'].str.replace("\n","")

In [22]:
df['Team & Contract'].value_counts()

Team & Contract
 IndiaFree                              29
 EcuadorFree                            24
 UruguayFree                            23
Oceânico FC2019 ~ 2023                  20
Atlético Clube Goianiense2019 ~ 2023    20
                                        ..
FC Barcelona2014 ~ 2022                  1
Liverpool2016 ~ 2023                     1
Liverpool2018 ~ 2024                     1
Paris Saint-Germain2018 ~ 2022           1
FC Bayern München2014 ~ 2023             1
Name: count, Length: 9023, dtype: int64

In [23]:
df['Team & Contract'].str[-11:].str.split("~").str[0]    # .astype(int)

0        2004
1        2018
2        2014
3        2015
4        2017
         ...
18974    2020
18975    2020
18976    2018
18977    2020
18978    2020
Name: Team & Contract, Length: 18979, dtype: object

In [24]:
# creating a function using def for sepetating the data of "Team & Contract" column 
def teamcleaner(x):
    if x.__contains__("On Loan"):
        return int(x.split(",")[1].split()[0]),int(x.split(",")[1].split()[0])+1,x.split(",")[0][:-6]
    
    elif x.__contains__("~"):
        return int(x[-11:].replace(" ",'').split("~")[0]),int(x[-11:].replace(" ",'').split("~")[1]),x[:-11]
    else:
        return 0,0,x

In [25]:
# Creating new columns for 'start, end year' and "team name" 
df[['Start Year', 'End Year', 'Team Name']] = list(map(teamcleaner,df['Team & Contract']))

In [26]:
df

,LongName,Nationality,Positions,Age,↓OVA,POT,Team & Contract,ID,Height,Weight,foot,BOV,BP,Growth,Joined,Value,Wage,Release Clause,Attacking,Crossing,Finishing,Heading Accuracy,Short Passing,Volleys,Skill,Dribbling,Curve,FK Accuracy,Long Passing,Ball Control,Movement,Acceleration,Sprint Speed,Agility,Reactions,Balance,Power,Shot Power,Jumping,Stamina,Strength,Long Shots,Mentality,Aggression,Interceptions,Positioning,Vision,Penalties,Composure,Defending,Marking,Standing Tackle,Sliding Tackle,Goalkeeping,GK Diving,GK Handling,GK Kicking,GK Positioning,GK Reflexes,Total Stats,Base Stats,W/F,SM,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits,Start Year,End Year,Team Name
0,Lionel Messi,Argentina,RW ST CF,33,93,93,FC Barcelona2004 ~ 2021,158023,"5'7""",159lbs,Left,93,RW,0,"Jul 1, 2004",€67.5M,€560K,€138.4M,429,85,95,70,91,88,470,96,93,94,91,96,451,91,80,91,94,95,389,86,68,72,69,94,347,44,40,93,95,75,96,91,32,35,24,54,6,11,15,14,8,2231,466,4 ★,4★,Medium,Low,5 ★,85,92,91,95,38,65,\n372,2004,2021,FC Barcelona
1,C. Ronaldo dos Santos Aveiro,Portugal,ST LW,35,92,92,Juventus2018 ~ 2022,20801,"6'2""",183lbs,Right,92,ST,0,"Jul 10, 2018",€46M,€220K,€75.9M,437,84,95,90,82,86,414,88,81,76,77,92,431,87,91,87,95,71,444,94,95,84,78,93,353,63,29,95,82,84,95,84,28,32,24,58,7,11,15,14,11,2221,464,4 ★,5★,High,Low,5 ★,89,93,81,89,35,77,\n344,2018,2022,Juventus
2,Jan Oblak,Slovenia,GK,27,91,93,Atlético Madrid2014 ~ 2023,200389,"6'2""",192lbs,Right,91,GK,2,"Jul 16, 2014",€75M,€125K,€159.4M,95,13,11,15,43,13,109,12,13,14,40,30,307,43,60,67,88,49,268,59,78,41,78,12,140,34,19,11,65,11,68,57,27,12,18,437,87,92,78,90,90,1413,489,3 ★,1★,Medium,Medium,3 ★,87,92,78,90,52,90,\n86,2014,2023,Atlético Madrid
3,Kevin De Bruyne,Belgium,CAM CM,29,91,91,Manchester City2015 ~ 2023,192985,"5'11""",154lbs,Right,91,CAM,0,"Aug 30, 2015",€87M,€370K,€161M,407,94,82,55,94,82,441,88,85,83,93,92,398,77,76,78,91,76,408,91,63,89,74,91,408,76,66,88,94,84,91,186,68,65,53,56,15,13,5,10,13,2304,485,5 ★,4★,High,High,4 ★,76,86,93,88,64,78,\n163,2015,2023,Manchester City
4,Neymar da Silva Santos Jr.,Brazil,LW CAM,28,91,91,Paris Saint-Germain2017 ~ 2022,190871,"5'9""",150lbs,Right,91,LW,0,"Aug 3, 2017",€90M,€270K,€166.5M,408,85,87,62,87,87,448,95,88,89,81,95,453,94,89,96,91,83,357,80,62,81,50,84,356,51,36,87,90,92,93,94,35,30,29,59,9,9,15,15,11,2175,451,5 ★,5★,High,Medium,5 ★,91,85,86,94,36,59,\n273,2017,2022,Paris Saint-Germain
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18974,Mengxuan Zhang,China PR,CB,21,47,52,Chongqing Dangdai Lifan FC SWM Team2020 ~ 2020,257710,"5'10""",154lbs,Right,49,CB,5,"Aug 1, 2020",€35K,€1K,€57K,141,23,16,45,31,26,111,19,21,22,25,24,279,60,56,45,48,70,223,35,65,55,45,23,179,44,50,25,25,35,40,148,45,56,47,53,12,13,8,14,6,1134,232,2 ★,2★,Low,Low,1 ★,58,23,26,27,50,48,2,2020,2020,Chongqing Dangdai Lifan FC SWM Team
18975,Vani Da Silva,England,ST,17,47,67,Oldham Athletic2020 ~ 2021,258736,"5'7""",128lbs,Right,51,CAM,20,"Aug 1, 2020",€60K,€500,€165K,202,27,47,36,45,47,208,53,43,31,37,44,339,69,70,67,53,80,231,50,50,55,35,41,186,33,11,43,49,50,45,42,18,11,13,48,11,13,9,9,6,1256,265,2 ★,2★,Medium,Medium,1 ★,70,46,40,53,16,40,3,2020,2021,Oldham Athletic
18976,Ao Xia,China PR,CB,21,47,55,Wuhan Zall2018 ~ 2022,247223,"5'10""",146lbs,Right,49,CB,8,"Jul 13, 2018",€40K,€1K,€70K,145,23,26,43,26,27,142,27,23,21,29,42,294,68,60,69,46,51,221,36,57,54,50,24,192,48,50,28,28,38,44,147,45,52,50,45,7,8,5,14,11,1186,255,2 ★,2★,Medium,Medium,1 ★,64,28,26,38,48,51,3,2018,2022,Wuhan Zall
18977,Ben Hough,England,CM,17,47,67,Oldham Athletic2020 ~ 2021,258760,"5'9""",143lbs,Right,51,CAM,20,"Aug 1, 2020",€60K,€500,€165K,211,38,42,40,56,35,219,46,40,35,50,48,305,63,64,61,51,66,226,48,58,43,47,30,193,40,23,47,47,36,38,116,32,44,40,45,12,10,9,6,8,1315,281,2 ★,2★,Medium,Medium,1 ★,64,40,48,49,35,45,5,2020,2021,Oldham Athletic
18978,Mateo Flores,Bolivia,CDM,19,47,63,Club Bolívar2020 ~ 2024,255958,"5'9""",150lbs,Right,48,CDM,16,"Jan 1, 2020",€60K,€500,€167K,191,32,27,48,52,32,198,45,31,32,47,43,298,55,59,59,50,75,223,41,55,47,47,33,206,57,45,30,39,35,36,129,43,41,45,56,10,8,15,9,14,1301,273,3 ★,2★,Medium,Medium,1 ★,57,32,43,48,44,49,2,2020,2024,Club Bolívar

In [27]:
# Dropping the Team & Contract column
df.drop(['Team & Contract'],axis=1,inplace=True)

In [28]:
df

,LongName,Nationality,Positions,Age,↓OVA,POT,ID,Height,Weight,foot,BOV,BP,Growth,Joined,Value,Wage,Release Clause,Attacking,Crossing,Finishing,Heading Accuracy,Short Passing,Volleys,Skill,Dribbling,Curve,FK Accuracy,Long Passing,Ball Control,Movement,Acceleration,Sprint Speed,Agility,Reactions,Balance,Power,Shot Power,Jumping,Stamina,Strength,Long Shots,Mentality,Aggression,Interceptions,Positioning,Vision,Penalties,Composure,Defending,Marking,Standing Tackle,Sliding Tackle,Goalkeeping,GK Diving,GK Handling,GK Kicking,GK Positioning,GK Reflexes,Total Stats,Base Stats,W/F,SM,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits,Start Year,End Year,Team Name
0,Lionel Messi,Argentina,RW ST CF,33,93,93,158023,"5'7""",159lbs,Left,93,RW,0,"Jul 1, 2004",€67.5M,€560K,€138.4M,429,85,95,70,91,88,470,96,93,94,91,96,451,91,80,91,94,95,389,86,68,72,69,94,347,44,40,93,95,75,96,91,32,35,24,54,6,11,15,14,8,2231,466,4 ★,4★,Medium,Low,5 ★,85,92,91,95,38,65,\n372,2004,2021,FC Barcelona
1,C. Ronaldo dos Santos Aveiro,Portugal,ST LW,35,92,92,20801,"6'2""",183lbs,Right,92,ST,0,"Jul 10, 2018",€46M,€220K,€75.9M,437,84,95,90,82,86,414,88,81,76,77,92,431,87,91,87,95,71,444,94,95,84,78,93,353,63,29,95,82,84,95,84,28,32,24,58,7,11,15,14,11,2221,464,4 ★,5★,High,Low,5 ★,89,93,81,89,35,77,\n344,2018,2022,Juventus
2,Jan Oblak,Slovenia,GK,27,91,93,200389,"6'2""",192lbs,Right,91,GK,2,"Jul 16, 2014",€75M,€125K,€159.4M,95,13,11,15,43,13,109,12,13,14,40,30,307,43,60,67,88,49,268,59,78,41,78,12,140,34,19,11,65,11,68,57,27,12,18,437,87,92,78,90,90,1413,489,3 ★,1★,Medium,Medium,3 ★,87,92,78,90,52,90,\n86,2014,2023,Atlético Madrid
3,Kevin De Bruyne,Belgium,CAM CM,29,91,91,192985,"5'11""",154lbs,Right,91,CAM,0,"Aug 30, 2015",€87M,€370K,€161M,407,94,82,55,94,82,441,88,85,83,93,92,398,77,76,78,91,76,408,91,63,89,74,91,408,76,66,88,94,84,91,186,68,65,53,56,15,13,5,10,13,2304,485,5 ★,4★,High,High,4 ★,76,86,93,88,64,78,\n163,2015,2023,Manchester City
4,Neymar da Silva Santos Jr.,Brazil,LW CAM,28,91,91,190871,"5'9""",150lbs,Right,91,LW,0,"Aug 3, 2017",€90M,€270K,€166.5M,408,85,87,62,87,87,448,95,88,89,81,95,453,94,89,96,91,83,357,80,62,81,50,84,356,51,36,87,90,92,93,94,35,30,29,59,9,9,15,15,11,2175,451,5 ★,5★,High,Medium,5 ★,91,85,86,94,36,59,\n273,2017,2022,Paris Saint-Germain
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18974,Mengxuan Zhang,China PR,CB,21,47,52,257710,"5'10""",154lbs,Right,49,CB,5,"Aug 1, 2020",€35K,€1K,€57K,141,23,16,45,31,26,111,19,21,22,25,24,279,60,56,45,48,70,223,35,65,55,45,23,179,44,50,25,25,35,40,148,45,56,47,53,12,13,8,14,6,1134,232,2 ★,2★,Low,Low,1 ★,58,23,26,27,50,48,2,2020,2020,Chongqing Dangdai Lifan FC SWM Team
18975,Vani Da Silva,England,ST,17,47,67,258736,"5'7""",128lbs,Right,51,CAM,20,"Aug 1, 2020",€60K,€500,€165K,202,27,47,36,45,47,208,53,43,31,37,44,339,69,70,67,53,80,231,50,50,55,35,41,186,33,11,43,49,50,45,42,18,11,13,48,11,13,9,9,6,1256,265,2 ★,2★,Medium,Medium,1 ★,70,46,40,53,16,40,3,2020,2021,Oldham Athletic
18976,Ao Xia,China PR,CB,21,47,55,247223,"5'10""",146lbs,Right,49,CB,8,"Jul 13, 2018",€40K,€1K,€70K,145,23,26,43,26,27,142,27,23,21,29,42,294,68,60,69,46,51,221,36,57,54,50,24,192,48,50,28,28,38,44,147,45,52,50,45,7,8,5,14,11,1186,255,2 ★,2★,Medium,Medium,1 ★,64,28,26,38,48,51,3,2018,2022,Wuhan Zall
18977,Ben Hough,England,CM,17,47,67,258760,"5'9""",143lbs,Right,51,CAM,20,"Aug 1, 2020",€60K,€500,€165K,211,38,42,40,56,35,219,46,40,35,50,48,305,63,64,61,51,66,226,48,58,43,47,30,193,40,23,47,47,36,38,116,32,44,40,45,12,10,9,6,8,1315,281,2 ★,2★,Medium,Medium,1 ★,64,40,48,49,35,45,5,2020,2021,Oldham Athletic
18978,Mateo Flores,Bolivia,CDM,19,47,63,255958,"5'9""",150lbs,Right,48,CDM,16,"Jan 1, 2020",€60K,€500,€167K,191,32,27,48,52,32,198,45,31,32,47,43,298,55,59,59,50,75,223,41,55,47,47,33,206,57,45,30,39,35,36,129,43,41,45,56,10,8,15,9,14,1301,273,3 ★,2★,Medium,Medium,1 ★,57,32,43,48,44,49,2,2020,2024,Club Bolívar

In [29]:
# changing height into "cm"
df['Height'] = df['Height'].str.replace('"','').str.split("'").str[0].astype(int)*30.48 + df['Height'].str.replace('"','').str.split("'").str[1].astype(int)*2.54

In [30]:
df

,LongName,Nationality,Positions,Age,↓OVA,POT,ID,Height,Weight,foot,BOV,BP,Growth,Joined,Value,Wage,Release Clause,Attacking,Crossing,Finishing,Heading Accuracy,Short Passing,Volleys,Skill,Dribbling,Curve,FK Accuracy,Long Passing,Ball Control,Movement,Acceleration,Sprint Speed,Agility,Reactions,Balance,Power,Shot Power,Jumping,Stamina,Strength,Long Shots,Mentality,Aggression,Interceptions,Positioning,Vision,Penalties,Composure,Defending,Marking,Standing Tackle,Sliding Tackle,Goalkeeping,GK Diving,GK Handling,GK Kicking,GK Positioning,GK Reflexes,Total Stats,Base Stats,W/F,SM,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits,Start Year,End Year,Team Name
0,Lionel Messi,Argentina,RW ST CF,33,93,93,158023,170.18,159lbs,Left,93,RW,0,"Jul 1, 2004",€67.5M,€560K,€138.4M,429,85,95,70,91,88,470,96,93,94,91,96,451,91,80,91,94,95,389,86,68,72,69,94,347,44,40,93,95,75,96,91,32,35,24,54,6,11,15,14,8,2231,466,4 ★,4★,Medium,Low,5 ★,85,92,91,95,38,65,\n372,2004,2021,FC Barcelona
1,C. Ronaldo dos Santos Aveiro,Portugal,ST LW,35,92,92,20801,187.96,183lbs,Right,92,ST,0,"Jul 10, 2018",€46M,€220K,€75.9M,437,84,95,90,82,86,414,88,81,76,77,92,431,87,91,87,95,71,444,94,95,84,78,93,353,63,29,95,82,84,95,84,28,32,24,58,7,11,15,14,11,2221,464,4 ★,5★,High,Low,5 ★,89,93,81,89,35,77,\n344,2018,2022,Juventus
2,Jan Oblak,Slovenia,GK,27,91,93,200389,187.96,192lbs,Right,91,GK,2,"Jul 16, 2014",€75M,€125K,€159.4M,95,13,11,15,43,13,109,12,13,14,40,30,307,43,60,67,88,49,268,59,78,41,78,12,140,34,19,11,65,11,68,57,27,12,18,437,87,92,78,90,90,1413,489,3 ★,1★,Medium,Medium,3 ★,87,92,78,90,52,90,\n86,2014,2023,Atlético Madrid
3,Kevin De Bruyne,Belgium,CAM CM,29,91,91,192985,180.34,154lbs,Right,91,CAM,0,"Aug 30, 2015",€87M,€370K,€161M,407,94,82,55,94,82,441,88,85,83,93,92,398,77,76,78,91,76,408,91,63,89,74,91,408,76,66,88,94,84,91,186,68,65,53,56,15,13,5,10,13,2304,485,5 ★,4★,High,High,4 ★,76,86,93,88,64,78,\n163,2015,2023,Manchester City
4,Neymar da Silva Santos Jr.,Brazil,LW CAM,28,91,91,190871,175.26,150lbs,Right,91,LW,0,"Aug 3, 2017",€90M,€270K,€166.5M,408,85,87,62,87,87,448,95,88,89,81,95,453,94,89,96,91,83,357,80,62,81,50,84,356,51,36,87,90,92,93,94,35,30,29,59,9,9,15,15,11,2175,451,5 ★,5★,High,Medium,5 ★,91,85,86,94,36,59,\n273,2017,2022,Paris Saint-Germain
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18974,Mengxuan Zhang,China PR,CB,21,47,52,257710,177.80,154lbs,Right,49,CB,5,"Aug 1, 2020",€35K,€1K,€57K,141,23,16,45,31,26,111,19,21,22,25,24,279,60,56,45,48,70,223,35,65,55,45,23,179,44,50,25,25,35,40,148,45,56,47,53,12,13,8,14,6,1134,232,2 ★,2★,Low,Low,1 ★,58,23,26,27,50,48,2,2020,2020,Chongqing Dangdai Lifan FC SWM Team
18975,Vani Da Silva,England,ST,17,47,67,258736,170.18,128lbs,Right,51,CAM,20,"Aug 1, 2020",€60K,€500,€165K,202,27,47,36,45,47,208,53,43,31,37,44,339,69,70,67,53,80,231,50,50,55,35,41,186,33,11,43,49,50,45,42,18,11,13,48,11,13,9,9,6,1256,265,2 ★,2★,Medium,Medium,1 ★,70,46,40,53,16,40,3,2020,2021,Oldham Athletic
18976,Ao Xia,China PR,CB,21,47,55,247223,177.80,146lbs,Right,49,CB,8,"Jul 13, 2018",€40K,€1K,€70K,145,23,26,43,26,27,142,27,23,21,29,42,294,68,60,69,46,51,221,36,57,54,50,24,192,48,50,28,28,38,44,147,45,52,50,45,7,8,5,14,11,1186,255,2 ★,2★,Medium,Medium,1 ★,64,28,26,38,48,51,3,2018,2022,Wuhan Zall
18977,Ben Hough,England,CM,17,47,67,258760,175.26,143lbs,Right,51,CAM,20,"Aug 1, 2020",€60K,€500,€165K,211,38,42,40,56,35,219,46,40,35,50,48,305,63,64,61,51,66,226,48,58,43,47,30,193,40,23,47,47,36,38,116,32,44,40,45,12,10,9,6,8,1315,281,2 ★,2★,Medium,Medium,1 ★,64,40,48,49,35,45,5,2020,2021,Oldham Athletic
18978,Mateo Flores,Bolivia,CDM,19,47,63,255958,175.26,150lbs,Right,48,CDM,16,"Jan 1, 2020",€60K,€500,€167K,191,32,27,48,52,32,198,45,31,32,47,43,298,55,59,59,50,75,223,41,55,47,47,33,206,57,45,30,39,35,36,129,43,41,45,56,10,8,15,9,14,1301,273,3 ★,2★,Medium,Medium,1 ★,57,32,43,48,44,49,2,2020,2024,Club Bolívar

In [31]:
df['Weight'] = df['Weight'].str.replace("lbs",'').astype(int)*0.453592 # incomplete

In [32]:

df

,LongName,Nationality,Positions,Age,↓OVA,POT,ID,Height,Weight,foot,BOV,BP,Growth,Joined,Value,Wage,Release Clause,Attacking,Crossing,Finishing,Heading Accuracy,Short Passing,Volleys,Skill,Dribbling,Curve,FK Accuracy,Long Passing,Ball Control,Movement,Acceleration,Sprint Speed,Agility,Reactions,Balance,Power,Shot Power,Jumping,Stamina,Strength,Long Shots,Mentality,Aggression,Interceptions,Positioning,Vision,Penalties,Composure,Defending,Marking,Standing Tackle,Sliding Tackle,Goalkeeping,GK Diving,GK Handling,GK Kicking,GK Positioning,GK Reflexes,Total Stats,Base Stats,W/F,SM,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits,Start Year,End Year,Team Name
0,Lionel Messi,Argentina,RW ST CF,33,93,93,158023,170.18,72.121128,Left,93,RW,0,"Jul 1, 2004",€67.5M,€560K,€138.4M,429,85,95,70,91,88,470,96,93,94,91,96,451,91,80,91,94,95,389,86,68,72,69,94,347,44,40,93,95,75,96,91,32,35,24,54,6,11,15,14,8,2231,466,4 ★,4★,Medium,Low,5 ★,85,92,91,95,38,65,\n372,2004,2021,FC Barcelona
1,C. Ronaldo dos Santos Aveiro,Portugal,ST LW,35,92,92,20801,187.96,83.007336,Right,92,ST,0,"Jul 10, 2018",€46M,€220K,€75.9M,437,84,95,90,82,86,414,88,81,76,77,92,431,87,91,87,95,71,444,94,95,84,78,93,353,63,29,95,82,84,95,84,28,32,24,58,7,11,15,14,11,2221,464,4 ★,5★,High,Low,5 ★,89,93,81,89,35,77,\n344,2018,2022,Juventus
2,Jan Oblak,Slovenia,GK,27,91,93,200389,187.96,87.089664,Right,91,GK,2,"Jul 16, 2014",€75M,€125K,€159.4M,95,13,11,15,43,13,109,12,13,14,40,30,307,43,60,67,88,49,268,59,78,41,78,12,140,34,19,11,65,11,68,57,27,12,18,437,87,92,78,90,90,1413,489,3 ★,1★,Medium,Medium,3 ★,87,92,78,90,52,90,\n86,2014,2023,Atlético Madrid
3,Kevin De Bruyne,Belgium,CAM CM,29,91,91,192985,180.34,69.853168,Right,91,CAM,0,"Aug 30, 2015",€87M,€370K,€161M,407,94,82,55,94,82,441,88,85,83,93,92,398,77,76,78,91,76,408,91,63,89,74,91,408,76,66,88,94,84,91,186,68,65,53,56,15,13,5,10,13,2304,485,5 ★,4★,High,High,4 ★,76,86,93,88,64,78,\n163,2015,2023,Manchester City
4,Neymar da Silva Santos Jr.,Brazil,LW CAM,28,91,91,190871,175.26,68.038800,Right,91,LW,0,"Aug 3, 2017",€90M,€270K,€166.5M,408,85,87,62,87,87,448,95,88,89,81,95,453,94,89,96,91,83,357,80,62,81,50,84,356,51,36,87,90,92,93,94,35,30,29,59,9,9,15,15,11,2175,451,5 ★,5★,High,Medium,5 ★,91,85,86,94,36,59,\n273,2017,2022,Paris Saint-Germain
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18974,Mengxuan Zhang,China PR,CB,21,47,52,257710,177.80,69.853168,Right,49,CB,5,"Aug 1, 2020",€35K,€1K,€57K,141,23,16,45,31,26,111,19,21,22,25,24,279,60,56,45,48,70,223,35,65,55,45,23,179,44,50,25,25,35,40,148,45,56,47,53,12,13,8,14,6,1134,232,2 ★,2★,Low,Low,1 ★,58,23,26,27,50,48,2,2020,2020,Chongqing Dangdai Lifan FC SWM Team
18975,Vani Da Silva,England,ST,17,47,67,258736,170.18,58.059776,Right,51,CAM,20,"Aug 1, 2020",€60K,€500,€165K,202,27,47,36,45,47,208,53,43,31,37,44,339,69,70,67,53,80,231,50,50,55,35,41,186,33,11,43,49,50,45,42,18,11,13,48,11,13,9,9,6,1256,265,2 ★,2★,Medium,Medium,1 ★,70,46,40,53,16,40,3,2020,2021,Oldham Athletic
18976,Ao Xia,China PR,CB,21,47,55,247223,177.80,66.224432,Right,49,CB,8,"Jul 13, 2018",€40K,€1K,€70K,145,23,26,43,26,27,142,27,23,21,29,42,294,68,60,69,46,51,221,36,57,54,50,24,192,48,50,28,28,38,44,147,45,52,50,45,7,8,5,14,11,1186,255,2 ★,2★,Medium,Medium,1 ★,64,28,26,38,48,51,3,2018,2022,Wuhan Zall
18977,Ben Hough,England,CM,17,47,67,258760,175.26,64.863656,Right,51,CAM,20,"Aug 1, 2020",€60K,€500,€165K,211,38,42,40,56,35,219,46,40,35,50,48,305,63,64,61,51,66,226,48,58,43,47,30,193,40,23,47,47,36,38,116,32,44,40,45,12,10,9,6,8,1315,281,2 ★,2★,Medium,Medium,1 ★,64,40,48,49,35,45,5,2020,2021,Oldham Athletic
18978,Mateo Flores,Bolivia,CDM,19,47,63,255958,175.26,68.038800,Right,48,CDM,16,"Jan 1, 2020",€60K,€500,€167K,191,32,27,48,52,32,198,45,31,32,47,43,298,55,59,59,50,75,223,41,55,47,47,33,206,57,45,30,39,35,36,129,43,41,45,56,10,8,15,9,14,1301,273,3 ★,2★,Medium,Medium,1 ★,57,32,43,48,44,49,2,2020,2024,Club Bolívar

In [33]:
df['Joined']=pd.to_datetime(df['Joined'])

In [34]:
def multiplier(x):
    if x.__contains__("M"):
        return float(x.replace("€","").replace("M",""))*1000000
    
    elif x.__contains__("K"):
        return float(x.replace("€","").replace("K",""))*1000
    else:
        return float(x.replace("€",""))

In [35]:
df['Value']=list(map(multiplier,df['Value']))

In [36]:
df['Wage']=list(map(multiplier,df['Wage']))

In [37]:
df['Release Clause']=list(map(multiplier,df['Release Clause']))

In [38]:
df

,LongName,Nationality,Positions,Age,↓OVA,POT,ID,Height,Weight,foot,BOV,BP,Growth,Joined,Value,Wage,Release Clause,Attacking,Crossing,Finishing,Heading Accuracy,Short Passing,Volleys,Skill,Dribbling,Curve,FK Accuracy,Long Passing,Ball Control,Movement,Acceleration,Sprint Speed,Agility,Reactions,Balance,Power,Shot Power,Jumping,Stamina,Strength,Long Shots,Mentality,Aggression,Interceptions,Positioning,Vision,Penalties,Composure,Defending,Marking,Standing Tackle,Sliding Tackle,Goalkeeping,GK Diving,GK Handling,GK Kicking,GK Positioning,GK Reflexes,Total Stats,Base Stats,W/F,SM,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits,Start Year,End Year,Team Name
0,Lionel Messi,Argentina,RW ST CF,33,93,93,158023,170.18,72.121128,Left,93,RW,0,2004-07-01,67500000.0,560000.0,138400000.0,429,85,95,70,91,88,470,96,93,94,91,96,451,91,80,91,94,95,389,86,68,72,69,94,347,44,40,93,95,75,96,91,32,35,24,54,6,11,15,14,8,2231,466,4 ★,4★,Medium,Low,5 ★,85,92,91,95,38,65,\n372,2004,2021,FC Barcelona
1,C. Ronaldo dos Santos Aveiro,Portugal,ST LW,35,92,92,20801,187.96,83.007336,Right,92,ST,0,2018-07-10,46000000.0,220000.0,75900000.0,437,84,95,90,82,86,414,88,81,76,77,92,431,87,91,87,95,71,444,94,95,84,78,93,353,63,29,95,82,84,95,84,28,32,24,58,7,11,15,14,11,2221,464,4 ★,5★,High,Low,5 ★,89,93,81,89,35,77,\n344,2018,2022,Juventus
2,Jan Oblak,Slovenia,GK,27,91,93,200389,187.96,87.089664,Right,91,GK,2,2014-07-16,75000000.0,125000.0,159400000.0,95,13,11,15,43,13,109,12,13,14,40,30,307,43,60,67,88,49,268,59,78,41,78,12,140,34,19,11,65,11,68,57,27,12,18,437,87,92,78,90,90,1413,489,3 ★,1★,Medium,Medium,3 ★,87,92,78,90,52,90,\n86,2014,2023,Atlético Madrid
3,Kevin De Bruyne,Belgium,CAM CM,29,91,91,192985,180.34,69.853168,Right,91,CAM,0,2015-08-30,87000000.0,370000.0,161000000.0,407,94,82,55,94,82,441,88,85,83,93,92,398,77,76,78,91,76,408,91,63,89,74,91,408,76,66,88,94,84,91,186,68,65,53,56,15,13,5,10,13,2304,485,5 ★,4★,High,High,4 ★,76,86,93,88,64,78,\n163,2015,2023,Manchester City
4,Neymar da Silva Santos Jr.,Brazil,LW CAM,28,91,91,190871,175.26,68.038800,Right,91,LW,0,2017-08-03,90000000.0,270000.0,166500000.0,408,85,87,62,87,87,448,95,88,89,81,95,453,94,89,96,91,83,357,80,62,81,50,84,356,51,36,87,90,92,93,94,35,30,29,59,9,9,15,15,11,2175,451,5 ★,5★,High,Medium,5 ★,91,85,86,94,36,59,\n273,2017,2022,Paris Saint-Germain
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18974,Mengxuan Zhang,China PR,CB,21,47,52,257710,177.80,69.853168,Right,49,CB,5,2020-08-01,35000.0,1000.0,57000.0,141,23,16,45,31,26,111,19,21,22,25,24,279,60,56,45,48,70,223,35,65,55,45,23,179,44,50,25,25,35,40,148,45,56,47,53,12,13,8,14,6,1134,232,2 ★,2★,Low,Low,1 ★,58,23,26,27,50,48,2,2020,2020,Chongqing Dangdai Lifan FC SWM Team
18975,Vani Da Silva,England,ST,17,47,67,258736,170.18,58.059776,Right,51,CAM,20,2020-08-01,60000.0,500.0,165000.0,202,27,47,36,45,47,208,53,43,31,37,44,339,69,70,67,53,80,231,50,50,55,35,41,186,33,11,43,49,50,45,42,18,11,13,48,11,13,9,9,6,1256,265,2 ★,2★,Medium,Medium,1 ★,70,46,40,53,16,40,3,2020,2021,Oldham Athletic
18976,Ao Xia,China PR,CB,21,47,55,247223,177.80,66.224432,Right,49,CB,8,2018-07-13,40000.0,1000.0,70000.0,145,23,26,43,26,27,142,27,23,21,29,42,294,68,60,69,46,51,221,36,57,54,50,24,192,48,50,28,28,38,44,147,45,52,50,45,7,8,5,14,11,1186,255,2 ★,2★,Medium,Medium,1 ★,64,28,26,38,48,51,3,2018,2022,Wuhan Zall
18977,Ben Hough,England,CM,17,47,67,258760,175.26,64.863656,Right,51,CAM,20,2020-08-01,60000.0,500.0,165000.0,211,38,42,40,56,35,219,46,40,35,50,48,305,63,64,61,51,66,226,48,58,43,47,30,193,40,23,47,47,36,38,116,32,44,40,45,12,10,9,6,8,1315,281,2 ★,2★,Medium,Medium,1 ★,64,40,48,49,35,45,5,2020,2021,Oldham Athletic
18978,Mateo Flores,Bolivia,CDM,19,47,63,255958,175.26,68.038800,Right,48,CDM,16,2020-01-01,60000.0,500.0,167000.0,191,32,27,48,52,32,198,45,31,32,47,43,298,55,59,59,50,75,223,41,55,47,47,33,206,57,45,30,39,35,36,129,43,41,45,56,10,8,15,9,14,1301,273,3 ★,2★,Medium,Medium,1 ★,57,32,43,48,44,49,2,2020,2024,Club Bolívar

In [39]:
df['W/F']=df['W/F'].str.replace("★","").str[0].astype(int)

In [40]:
df['SM']=df['SM'].str.replace("★","").str[0].astype(int)

In [41]:
df['IR']=df['IR'].str.replace("★","").str[0].astype(int)

In [42]:
df

,LongName,Nationality,Positions,Age,↓OVA,POT,ID,Height,Weight,foot,BOV,BP,Growth,Joined,Value,Wage,Release Clause,Attacking,Crossing,Finishing,Heading Accuracy,Short Passing,Volleys,Skill,Dribbling,Curve,FK Accuracy,Long Passing,Ball Control,Movement,Acceleration,Sprint Speed,Agility,Reactions,Balance,Power,Shot Power,Jumping,Stamina,Strength,Long Shots,Mentality,Aggression,Interceptions,Positioning,Vision,Penalties,Composure,Defending,Marking,Standing Tackle,Sliding Tackle,Goalkeeping,GK Diving,GK Handling,GK Kicking,GK Positioning,GK Reflexes,Total Stats,Base Stats,W/F,SM,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits,Start Year,End Year,Team Name
0,Lionel Messi,Argentina,RW ST CF,33,93,93,158023,170.18,72.121128,Left,93,RW,0,2004-07-01,67500000.0,560000.0,138400000.0,429,85,95,70,91,88,470,96,93,94,91,96,451,91,80,91,94,95,389,86,68,72,69,94,347,44,40,93,95,75,96,91,32,35,24,54,6,11,15,14,8,2231,466,4,4,Medium,Low,5,85,92,91,95,38,65,\n372,2004,2021,FC Barcelona
1,C. Ronaldo dos Santos Aveiro,Portugal,ST LW,35,92,92,20801,187.96,83.007336,Right,92,ST,0,2018-07-10,46000000.0,220000.0,75900000.0,437,84,95,90,82,86,414,88,81,76,77,92,431,87,91,87,95,71,444,94,95,84,78,93,353,63,29,95,82,84,95,84,28,32,24,58,7,11,15,14,11,2221,464,4,5,High,Low,5,89,93,81,89,35,77,\n344,2018,2022,Juventus
2,Jan Oblak,Slovenia,GK,27,91,93,200389,187.96,87.089664,Right,91,GK,2,2014-07-16,75000000.0,125000.0,159400000.0,95,13,11,15,43,13,109,12,13,14,40,30,307,43,60,67,88,49,268,59,78,41,78,12,140,34,19,11,65,11,68,57,27,12,18,437,87,92,78,90,90,1413,489,3,1,Medium,Medium,3,87,92,78,90,52,90,\n86,2014,2023,Atlético Madrid
3,Kevin De Bruyne,Belgium,CAM CM,29,91,91,192985,180.34,69.853168,Right,91,CAM,0,2015-08-30,87000000.0,370000.0,161000000.0,407,94,82,55,94,82,441,88,85,83,93,92,398,77,76,78,91,76,408,91,63,89,74,91,408,76,66,88,94,84,91,186,68,65,53,56,15,13,5,10,13,2304,485,5,4,High,High,4,76,86,93,88,64,78,\n163,2015,2023,Manchester City
4,Neymar da Silva Santos Jr.,Brazil,LW CAM,28,91,91,190871,175.26,68.038800,Right,91,LW,0,2017-08-03,90000000.0,270000.0,166500000.0,408,85,87,62,87,87,448,95,88,89,81,95,453,94,89,96,91,83,357,80,62,81,50,84,356,51,36,87,90,92,93,94,35,30,29,59,9,9,15,15,11,2175,451,5,5,High,Medium,5,91,85,86,94,36,59,\n273,2017,2022,Paris Saint-Germain
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18974,Mengxuan Zhang,China PR,CB,21,47,52,257710,177.80,69.853168,Right,49,CB,5,2020-08-01,35000.0,1000.0,57000.0,141,23,16,45,31,26,111,19,21,22,25,24,279,60,56,45,48,70,223,35,65,55,45,23,179,44,50,25,25,35,40,148,45,56,47,53,12,13,8,14,6,1134,232,2,2,Low,Low,1,58,23,26,27,50,48,2,2020,2020,Chongqing Dangdai Lifan FC SWM Team
18975,Vani Da Silva,England,ST,17,47,67,258736,170.18,58.059776,Right,51,CAM,20,2020-08-01,60000.0,500.0,165000.0,202,27,47,36,45,47,208,53,43,31,37,44,339,69,70,67,53,80,231,50,50,55,35,41,186,33,11,43,49,50,45,42,18,11,13,48,11,13,9,9,6,1256,265,2,2,Medium,Medium,1,70,46,40,53,16,40,3,2020,2021,Oldham Athletic
18976,Ao Xia,China PR,CB,21,47,55,247223,177.80,66.224432,Right,49,CB,8,2018-07-13,40000.0,1000.0,70000.0,145,23,26,43,26,27,142,27,23,21,29,42,294,68,60,69,46,51,221,36,57,54,50,24,192,48,50,28,28,38,44,147,45,52,50,45,7,8,5,14,11,1186,255,2,2,Medium,Medium,1,64,28,26,38,48,51,3,2018,2022,Wuhan Zall
18977,Ben Hough,England,CM,17,47,67,258760,175.26,64.863656,Right,51,CAM,20,2020-08-01,60000.0,500.0,165000.0,211,38,42,40,56,35,219,46,40,35,50,48,305,63,64,61,51,66,226,48,58,43,47,30,193,40,23,47,47,36,38,116,32,44,40,45,12,10,9,6,8,1315,281,2,2,Medium,Medium,1,64,40,48,49,35,45,5,2020,2021,Oldham Athletic
18978,Mateo Flores,Bolivia,CDM,19,47,63,255958,175.26,68.038800,Right,48,CDM,16,2020-01-01,60000.0,500.0,167000.0,191,32,27,48,52,32,198,45,31,32,47,43,298,55,59,59,50,75,223,41,55,47,47,33,206,57,45,30,39,35,36,129,43,41,45,56,10,8,15,9,14,1301,273,3,2,Medium,Medium,1,57,32,43,48,44,49,2,2020,2024,Club Bolívar

In [43]:
# Hits column cleaning
df.loc[df[~df['Hits'].str.contains("\n").isnull()]['Hits'].str.replace("\n",'').index,"Hits"] = list(map(multiplier,df[~df['Hits'].str.contains("\n").isnull()]['Hits'].str.replace("\n",'')))

In [44]:
df

,LongName,Nationality,Positions,Age,↓OVA,POT,ID,Height,Weight,foot,BOV,BP,Growth,Joined,Value,Wage,Release Clause,Attacking,Crossing,Finishing,Heading Accuracy,Short Passing,Volleys,Skill,Dribbling,Curve,FK Accuracy,Long Passing,Ball Control,Movement,Acceleration,Sprint Speed,Agility,Reactions,Balance,Power,Shot Power,Jumping,Stamina,Strength,Long Shots,Mentality,Aggression,Interceptions,Positioning,Vision,Penalties,Composure,Defending,Marking,Standing Tackle,Sliding Tackle,Goalkeeping,GK Diving,GK Handling,GK Kicking,GK Positioning,GK Reflexes,Total Stats,Base Stats,W/F,SM,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits,Start Year,End Year,Team Name
0,Lionel Messi,Argentina,RW ST CF,33,93,93,158023,170.18,72.121128,Left,93,RW,0,2004-07-01,67500000.0,560000.0,138400000.0,429,85,95,70,91,88,470,96,93,94,91,96,451,91,80,91,94,95,389,86,68,72,69,94,347,44,40,93,95,75,96,91,32,35,24,54,6,11,15,14,8,2231,466,4,4,Medium,Low,5,85,92,91,95,38,65,372.0,2004,2021,FC Barcelona
1,C. Ronaldo dos Santos Aveiro,Portugal,ST LW,35,92,92,20801,187.96,83.007336,Right,92,ST,0,2018-07-10,46000000.0,220000.0,75900000.0,437,84,95,90,82,86,414,88,81,76,77,92,431,87,91,87,95,71,444,94,95,84,78,93,353,63,29,95,82,84,95,84,28,32,24,58,7,11,15,14,11,2221,464,4,5,High,Low,5,89,93,81,89,35,77,344.0,2018,2022,Juventus
2,Jan Oblak,Slovenia,GK,27,91,93,200389,187.96,87.089664,Right,91,GK,2,2014-07-16,75000000.0,125000.0,159400000.0,95,13,11,15,43,13,109,12,13,14,40,30,307,43,60,67,88,49,268,59,78,41,78,12,140,34,19,11,65,11,68,57,27,12,18,437,87,92,78,90,90,1413,489,3,1,Medium,Medium,3,87,92,78,90,52,90,86.0,2014,2023,Atlético Madrid
3,Kevin De Bruyne,Belgium,CAM CM,29,91,91,192985,180.34,69.853168,Right,91,CAM,0,2015-08-30,87000000.0,370000.0,161000000.0,407,94,82,55,94,82,441,88,85,83,93,92,398,77,76,78,91,76,408,91,63,89,74,91,408,76,66,88,94,84,91,186,68,65,53,56,15,13,5,10,13,2304,485,5,4,High,High,4,76,86,93,88,64,78,163.0,2015,2023,Manchester City
4,Neymar da Silva Santos Jr.,Brazil,LW CAM,28,91,91,190871,175.26,68.038800,Right,91,LW,0,2017-08-03,90000000.0,270000.0,166500000.0,408,85,87,62,87,87,448,95,88,89,81,95,453,94,89,96,91,83,357,80,62,81,50,84,356,51,36,87,90,92,93,94,35,30,29,59,9,9,15,15,11,2175,451,5,5,High,Medium,5,91,85,86,94,36,59,273.0,2017,2022,Paris Saint-Germain
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18974,Mengxuan Zhang,China PR,CB,21,47,52,257710,177.80,69.853168,Right,49,CB,5,2020-08-01,35000.0,1000.0,57000.0,141,23,16,45,31,26,111,19,21,22,25,24,279,60,56,45,48,70,223,35,65,55,45,23,179,44,50,25,25,35,40,148,45,56,47,53,12,13,8,14,6,1134,232,2,2,Low,Low,1,58,23,26,27,50,48,2,2020,2020,Chongqing Dangdai Lifan FC SWM Team
18975,Vani Da Silva,England,ST,17,47,67,258736,170.18,58.059776,Right,51,CAM,20,2020-08-01,60000.0,500.0,165000.0,202,27,47,36,45,47,208,53,43,31,37,44,339,69,70,67,53,80,231,50,50,55,35,41,186,33,11,43,49,50,45,42,18,11,13,48,11,13,9,9,6,1256,265,2,2,Medium,Medium,1,70,46,40,53,16,40,3,2020,2021,Oldham Athletic
18976,Ao Xia,China PR,CB,21,47,55,247223,177.80,66.224432,Right,49,CB,8,2018-07-13,40000.0,1000.0,70000.0,145,23,26,43,26,27,142,27,23,21,29,42,294,68,60,69,46,51,221,36,57,54,50,24,192,48,50,28,28,38,44,147,45,52,50,45,7,8,5,14,11,1186,255,2,2,Medium,Medium,1,64,28,26,38,48,51,3,2018,2022,Wuhan Zall
18977,Ben Hough,England,CM,17,47,67,258760,175.26,64.863656,Right,51,CAM,20,2020-08-01,60000.0,500.0,165000.0,211,38,42,40,56,35,219,46,40,35,50,48,305,63,64,61,51,66,226,48,58,43,47,30,193,40,23,47,47,36,38,116,32,44,40,45,12,10,9,6,8,1315,281,2,2,Medium,Medium,1,64,40,48,49,35,45,5,2020,2021,Oldham Athletic
18978,Mateo Flores,Bolivia,CDM,19,47,63,255958,175.26,68.038800,Right,48,CDM,16,2020-01-01,60000.0,500.0,167000.0,191,32,27,48,52,32,198,45,31,32,47,43,298,55,59,59,50,75,223,41,55,47,47,33,206,57,45,30,39,35,36,129,43,41,45,56,10,8,15,9,14,1301,273,3,2,Medium,Medium,1,57,32,43,48,44,49,2,2020,2024,Club Bolívar